### ISSUE TITLE
Add location where the font is located (local server or extern)

### ISSUE THREAD

**Issue by dervelli** [andy-portmen/font-finder#12]
I love your „Font Finder“ Add-On and i have a request for the next Update:
GDPR doesnt allow Google Fonts if there aren’t local hosted (and performance is much better). So maybe you would like to add a location field where i can see (as a website developer) the font location. Will be much easier than all the way over the FF inspector.

Cheers
Velli

**Comment by andy-portmen** [comment]
Thanks for the feature request. The extension will display local/remote keywords next to the font-name as of 0.3.4 release. For remote fonts, you will get more info if you place the mouse over the element in the inspector window. Unfortunately, due to security considerations, it is not possible to parse the font origin
